hpc<-read.table("household_power_consumption.txt", header=TRUE, sep = ";", stringsAsFactors=FALSE)
newDates<-as.Date(hpc$Date, format  = "%d/%m/%Y")
newHpc<-lapply(hpc[,3:9], function(x) as.numeric(x))
newHpc<-as.data.frame(newHpc)
hpc2<-cbind(hpc[,1:2], newHpc)
hpc2$Date<-newDates
finalHpc1<-filter(hpc2, Date=="2007-02-01")
finalHpc2<-filter(hpc2, Date=="2007-02-02")
finalHpc<-rbind(finalHpc1, finalHpc2)
newDate<-as.Date(finalHpc$Date, format  = "%d/%m/%y")
finalHpc$Date<-newDate
test<-paste(as.character(finalHpc$Date), finalHpc$Time)
test<-mutate(finalHpc, newDate=test)
finalHpc<-test
finalHpc$newDate<-strptime(finalHpc$newDate, format="%F %H:%M:%S")
par(mfrow=c(2,2))
with(finalHpc, plot(newDate, Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab=""))
with(finalHpc, plot(newDate, Voltage, type="l", ylab="Voltage", xlab="datetime"))
with(finalHpc, plot(newDate, Sub_metering_3, type="l", ylim=c(0,38), ylab="Energy sub metering", xlab="", col="blue"))
par(new=T)
with(finalHpc, plot(newDate, Sub_metering_1, type="l", ylim=c(0,38), ylab="", xlab=""))
par(new=T)
with(finalHpc, plot(newDate, Sub_metering_2, type="l", ylim=c(0,38), ylab="", xlab="", col="red"))
legend("topright", col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1)
with(finalHpc, plot(newDate, Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime"))